### ISSUE TITLE
withPseudoState.js:194 DOMException: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule '.iJhULf :focus:not(:focus-visible), .pseudo-focus.pseudo-focus-visible .iJhULf :not() { box-shadow: none; }'.

### ISSUE THREAD

**Issue by isc30** [Ergosign/storybook-addon-pseudo-states#47]
**Describe the bug**
`withPseudoState.js:194 DOMException: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule '.iJhULf :focus:not(:focus-visible), .pseudo-focus.pseudo-focus-visible .iJhULf :not() { box-shadow: none; }'.`

**To Reproduce**
Have a CSS with the following content:

```css
&:focus {
  box-shadow: 0 0 4px red;

  &:not(:focus-visible) {
    box-shadow: none;
  }
}
```

**Expected behavior**
It should work
