### ISSUE TITLE
Hover style doesn't work with @media (hover: hover)

### ISSUE THREAD

**Issue by Znegl** [Ergosign/storybook-addon-pseudo-states#75]
**Describe the bug**
When wrapping `:hover` style in the media query `@media (hover: hover)` in the component stylesheet, the plugin doesn't apply it.

**To Reproduce**
1. Create a component with something like the following style in it:
```scss
.some-component {
  color: blue;

  @media (hover: hover) {
    &:hover {
      color: red;
    }
  }
}
```
3. Run Storybook
4. Try setting the hover-state using the psudo state plugin
5. See error

**Expected behavior**
I would expect the defined hover style to be applied.

**Screenshots**
—

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 119

**Additional context**
The plugin works as expected when I remove the media query, but introduces hover bugs for users of touch devices instead.
